development:
  adapter: sqlite3
  database: db/spree_development.sqlite3
  timeout: 5000
  pool: 5
test:
  adapter: sqlite3
  database: db/spree_test.sqlite3
  timeout: 5000
  pool: 5
production:
  adapter: sqlite3
  database: db/spree_production.sqlite3
  timeout: 5000
  pool: 5
